default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: turning_point_code_academy_development
  username: megagig
  password: password
  host: localhost
test:
  <<: *default
  database: turning_point_code_academy_test
  username: megagig
  password: password
  host: localhost
production:
  <<: *default
  database: turning_point_code_academy_production
  username: turning_point_code_academy
  password: <%= ENV["TURNING_POINT_CODE_ACADEMY_DATABASE_PASSWORD"] %>
